name: mitask
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  equatable: ^2.0.7
  flutter_bloc: ^9.1.1
  dartz: ^0.10.1
  sqflite: ^2.4.2
  uuid: ^4.5.1
  path: ^1.9.1
  shared_preferences: ^2.5.3
  get_it: ^8.2.0
  flutter_svg: ^2.2.1
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Thin.ttf
          weight: 100 # Thin
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300 # Light
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400 # Regular (Default)
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500 # Medium
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600 # SemiBold
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700 # Bold
